### ISSUE TITLE
weird error on cluster for study pg_238 tree109, aln Tr5276-M3938-mod.nex

### ISSUE THREAD

**Issue by LunaSare** [McTavishLab/physcraper#105]
Running 
```
physcraper_run.py -s pg_238 -t tree109 -a ../physcraperex/data-raw/alignments/Tr5276-M3938-mod.nex -as nexus  -db /branchinecta/shared/local_blast_db -o ../physcraperex/data/schoch_ascomycota_2_2020.06.06
```

Pasting here las lines of output
```
blasting seq otu63394
blasting seq otu63090
blasting seq otu63150
blasting seq otu63152
blasting seq otu63224
blasting seq otu63360
blasting seq otu63495
blasting seq otu63494
blasting seq otu63307
blasting seq otu63219
blasting seq otu63264
blasting seq otu63314
blasting seq otu63343
blasting seq otu63134
blasting seq otu63133
blasting seq otu63103
blasting seq otu63104
reading /home/lsanchezreyes2/pj_physcraper/physcraperex/data/schoch_ascomycota_2_2020.06.06/run_Tr5276-M3938-mod/blast_run_Tr5276-M3938-mod/otu63431.txt
sh: blastdbcmd: command not found
Traceback (most recent call last):
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/venv-physcraper/bin/physcraper_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/bin/physcraper_run.py", line 193, in <module>
    scraper.est_full_tree()
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/physcraper/scrape.py", line 1109, in est_full_tree
    alignment = self.align_new_seqs()
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/physcraper/scrape.py", line 914, in align_new_seqs
    self.read_blast_wrapper()
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/physcraper/scrape.py", line 562, in read_blast_wrapper
    self.read_local_blast_query(fn_path)
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/physcraper/scrape.py", line 351, in read_local_blast_query
    full_seq = self.get_full_seq(gb_acc, sseq)
  File "/home/lsanchezreyes2/pj_physcraper/physcraper/physcraper/scrape.py", line 392, in get_full_seq
    f = open(seq_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lsanchezreyes2/pj_physcraper/physcraper/taxonomy/downloaded_ncbi_sequences/AY640984.1.fasta'
```

**Comment by snacktavish** [comment]
Ah, that was my fault on the cluster install of the ncbi command line tools. blastdbcmd comes with the ncbi blast command line tools, but I only added blastn to the path. I fixed it and it should work now.

**Comment by LunaSare** [comment]
Added clearer error message for this on https://github.com/McTavishLab/physcraper/pull/106
