### ISSUE TITLE
writeinfofiles is not defined

### ISSUE THREAD

**Issue by blubbundbla** [McTavishLab/physcraper#133]
command: physcraper_run.py -s pg_55 -t tree5864 -tb -o pg_55

.Traceback (most recent call last):
  File "/root/physcraper_27072020/venv3/bin/physcraper_run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/physcraper_27072020/physcraper-main/bin/physcraper_run.py", line 220, in <module>
    scraper.calculate_final_tree(boot_reps = boot_reps)
  File "/root/physcraper_27072020/physcraper-main/physcraper/scrape.py", line 1215, in calculate_final_tree
    besttreepath = self.est_full_tree()
  File "/root/physcraper_27072020/physcraper-main/physcraper/scrape.py", line 1122, in est_full_tree
    alignment = self.align_new_seqs()
  File "/root/physcraper_27072020/physcraper-main/physcraper/scrape.py", line 931, in align_new_seqs
    self.read_blast_wrapper()
  File "/root/physcraper_27072020/physcraper-main/physcraper/scrape.py", line 580, in read_blast_wrapper
    self.read_webbased_blast_query(fn_path)
  File "/root/physcraper_27072020/physcraper-main/physcraper/scrape.py", line 540, in read_webbased_blast_query
    writeinfofiles.write_not_added_info(self, gb_id, "evalue threshold not passed")
NameError: name 'writeinfofiles' is not defined

**Comment by snacktavish** [comment]
Good catch! this should be fixed in https://github.com/McTavishLab/physcraper/commit/c0ee604da27368098315fc41cbbfe3fadc632c44

I'm just running some checks now.

**Comment by snacktavish** [comment]
My first fix introduced a new bug! But I have fixed both now, and merged to main. Should work now!
