### ISSUE TITLE
Tree not found?

### ISSUE THREAD

**Issue by blubbundbla** [McTavishLab/physcraper#138]
Trying a random example: 
physcraper_run.py -s pg_127 -t tree804  -tb -db PATH_TO_LOCAL -o pg_127

Traceback (most recent call last):
  File "/root/physcraper_27072020/venv3/bin/physcraper_run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/physcraper_27072020/physcraper-main/bin/physcraper_run.py", line 180, in <module>
    configfile = conf)
  File "/root/physcraper_27072020/physcraper-main/physcraper/opentree_helpers.py", line 371, in scraper_from_opentree
    tree_id=tree_id)
  File "/root/physcraper_27072020/physcraper-main/physcraper/opentree_helpers.py", line 259, in generate_ATT_from_phylesystem
    return_format="otu_id"))
TypeError: 'NoneType' object is not iterable

**Comment by snacktavish** [comment]
Ah, it looks like this error happens when the ingroup isn't specified in the input tree. I'll add a fix.

**Comment by snacktavish** [comment]
Fixed in https://github.com/McTavishLab/physcraper/commit/e2cf02bd90e42e84ae23968631bdd66bf35f72b3, merged to main
