### ISSUE TITLE
undefined character

### ISSUE THREAD

**Issue by jtfield** [McTavishLab/physcraper#179]
Installed using the docker installation methods (docker pull, docker run, etc).

Pulled from a find_trees.py result for: Neisseria

time physcraper_run.py --study_id pg_2757 --tree_id tree6369 --treebase --no_est --output pg_2757
No config file, using defaults
Configuration Settings
[blast]
Entrez.email = None
e_value_thresh = 1e-05
hitlist_size = 10
location = remote
localblastdb = None
num_threads = 4
delay = 90
[physcraper]
spp_threshold = 5
min_length = 0.8
max_length = 1.2

downloading best match alignment from treebase to pg_2757/pg_2757tree6369.aln
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 850, in parse_characters_format
    state = char_matrix.default_state_alphabet[symbol]
  File "/usr/local/lib/python3.8/dist-packages/dendropy/datamodel/charstatemodel.py", line 792, in __getitem__
    return self._full_symbol_state_map[key]
KeyError: 'U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/physcraper_run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/project/physcraper/bin/physcraper_run.py", line 215, in <module>
    dataset = physcraper.opentree_helpers.get_dataset_from_treebase(study_id)
  File "/project/physcraper/physcraper/opentree_helpers.py", line 410, in get_dataset_from_treebase
    dna = DataSet.get(url=url, schema="nexml")
  File "/usr/local/lib/python3.8/dist-packages/dendropy/datamodel/datasetmodel.py", line 188, in get
    return cls._get_from(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/datamodel/basemodel.py", line 160, in _get_from
    return cls.get_from_url(src=src, schema=schema, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/datamodel/basemodel.py", line 276, in get_from_url
    return cls._parse_and_create_from_stream(
  File "/usr/local/lib/python3.8/dist-packages/dendropy/datamodel/datasetmodel.py", line 123, in _parse_and_create_from_stream
    reader.read_dataset(
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/ioservice.py", line 251, in read_dataset
    product = self._read(stream=stream,
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 291, in _read
    self._parse_document(xml_doc)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 342, in _parse_document
    self._parse_char_matrices(xml_root)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 392, in _parse_char_matrices
    nxc.parse_char_matrix(char_matrix_element)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 654, in parse_char_matrix
    self.parse_characters_format(nxformat, data_type, char_matrix)
  File "/usr/local/lib/python3.8/dist-packages/dendropy/dataio/nexmlreader.py", line 852, in parse_characters_format
    raise Exception("'{}' is not a recognized symbol for the state alphabet for the '{}' data type".format(symbol, data_type))
Exception: 'U' is not a recognized symbol for the state alphabet for the 'protein' data type

real	0m5.144s
user	0m1.453s
sys	0m0.686s

**Comment by snacktavish** [comment]
It is an amino acid alignment - https://treebase.org/treebase-web/search/study/summary.html?id=14910
But we should catch that before this point!

**Comment by LunaSare** [comment]
Getting similar error with 

`time physcraper_run.py --study_id pg_2407 --tree_id tree5076 --search_taxon ott:913935 --treebase --bootstrap_reps 2 --output pg_2407`

**Comment by snacktavish** [comment]
> downloading best match alignment from treebase to pg_2407/pg_2407tree5076.aln

> ERROR: Problems reading the input data from treebase:
> DENDROPY ERROR:''U' is not a recognized symbol for the state alphabet for the 'protein' data type'
> 
> It appears this may not be a DNA alignment - physcraper can only use DNA currently.
> Investigate, and potentialy download alignment directly at 
> https://raw.githubusercontent.com/TreeBASE/supertreebase/master/data/treebase/S1013.xml

now returns a sensical error message, pointing to the treebase file as the problem
